import type { KnowledgeDoc, KnowledgeImage } from "./types";

export const mockDocs: KnowledgeDoc[] = [
  {
    id: "kb1",
    name: "智慧交通同类业绩汇编.docx",
    tags: ["业绩", "交通"],
    chunks: 42,
    updated: "3 天前",
    category: "业绩材料",
  },
  {
    id: "kb2",
    name: "等保三级建设方案模板.md",
    tags: ["安全", "模板"],
    chunks: 28,
    updated: "1 周前",
    category: "规范模板",
  },
  {
    id: "kb3",
    name: "微服务高可用部署白皮书.pdf",
    tags: ["架构"],
    chunks: 65,
    updated: "2 周前",
    category: "技术方案",
  },
  {
    id: "kb4",
    name: "运维 SLA 与培训大纲.docx",
    tags: ["运维", "培训"],
    chunks: 19,
    updated: "1 月前",
    category: "运维服务",
  },
];

/** 占位图：使用 CSS 渐变 data-uri 风格的纯色块由页面渲染，此处给稳定 id 与元数据 */
export const mockImages: KnowledgeImage[] = [
  {
    id: "img1",
    name: "系统总体架构图.png",
    thumbUrl: "",
    url: "",
    tags: ["架构", "示意图"],
    category: "架构图",
    width: 1600,
    height: 900,
    sizeLabel: "428 KB",
    caption: "云边协同总体架构，含接入层、能力层、业务层与展示层",
    updatedAt: "2026-07-08T10:00:00+08:00",
  },
  {
    id: "img2",
    name: "部署拓扑-双机房.png",
    thumbUrl: "",
    url: "",
    tags: ["部署", "高可用"],
    category: "部署图",
    width: 1400,
    height: 800,
    sizeLabel: "356 KB",
    caption: "双机房容器编排与故障切换拓扑",
    updatedAt: "2026-07-07T15:20:00+08:00",
  },
  {
    id: "img3",
    name: "项目实施甘特示意.png",
    thumbUrl: "",
    url: "",
    tags: ["进度", "实施"],
    category: "进度图",
    width: 1200,
    height: 600,
    sizeLabel: "210 KB",
    caption: "180 日历天实施里程碑横道示意",
    updatedAt: "2026-07-06T09:10:00+08:00",
  },
  {
    id: "img4",
    name: "指挥大屏效果图.jpg",
    thumbUrl: "",
    url: "",
    tags: ["可视化", "大屏"],
    category: "效果图",
    width: 1920,
    height: 1080,
    sizeLabel: "1.2 MB",
    caption: "交通运行监测与指挥调度大屏效果",
    updatedAt: "2026-07-05T18:00:00+08:00",
  },
  {
    id: "img5",
    name: "等保防护体系.png",
    thumbUrl: "",
    url: "",
    tags: ["安全", "等保"],
    category: "架构图",
    width: 1300,
    height: 860,
    sizeLabel: "390 KB",
    caption: "等保三级安全防护分层示意",
    updatedAt: "2026-07-04T11:30:00+08:00",
  },
  {
    id: "img6",
    name: "组织架构与人员.png",
    thumbUrl: "",
    url: "",
    tags: ["团队", "组织"],
    category: "组织图",
    width: 1100,
    height: 700,
    sizeLabel: "188 KB",
    caption: "项目组织与岗位职责结构",
    updatedAt: "2026-07-03T14:00:00+08:00",
  },
];

export const imageCategories = [
  "全部",
  "架构图",
  "部署图",
  "进度图",
  "效果图",
  "组织图",
  "未分类",
];
